kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: build-and-deploy-
spec:
  pipelineRef:
    name: build-and-deploy
  workspaces:
    - name: build-workspace
      persistentVolumeClaim:
        claimName: build-workspace-pvc
    - name: maven-settings
      emptyDir: {}
